# This file is used to run Schemathesis tests on every pull request
# It test the implementation of the API against the schema
name: Schemathesis Tests

on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  changes-check:
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.filter.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            any_changed:
              - 'junqo_back/**'
              - '.github/workflows/api-tests.yml'

  api-tests:
    needs: changes-check
    if: github.event_name == 'workflow_dispatch' || github.event.action == 'opened' || (github.event.action == 'synchronize' && needs.changes-check.outputs.any_changed == 'true')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Database configuration
      run: |
        echo "${{ secrets.DATABASE_PASSWORD }}" > db_password.conf

    - name: Start containers
      run: docker compose -f docker-compose.dev.yaml up -d --build

    - name: Run Schemathesis tests
      uses: schemathesis/action@v1
      with:
        schema: "http://back:4200/graphql"
        token: ${{ secrets.SCHEMATHESIS_TOKEN }}

    - name: Stop containers
      if: always()
      run: docker compose down
