# Launch tests for the backend
name: Backend Tests

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "junqo_back/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the Node.js version you are using

    - name: Install dependencies
      working-directory: junqo_back
      run: npm install

    - name: Run tests
      working-directory: junqo_back
      run: npm test
:bulb: Codebase verification

Update Flutter version in GitHub Actions workflow to meet project requirements.

The current workflow specifies Flutter version 3.0.0, which does not satisfy the project's SDK constraints (>=3.4.3 <4.0.0) defined in pubspec.yaml. To ensure compatibility and prevent potential build issues, please update the Flutter version as follows:

- name: Set up Flutter  
  uses: subosito/flutter-action@v2  
  with:  
    flutter-version: '3.4.3' # Update to at least 3.4.3 as specified in pubspec.yaml  
Alternatively, you can set it to a newer stable version if it aligns with your project's requirements.

Update Flutter version and verify project compatibility.

The checkout and Flutter setup steps are correct, but the specified Flutter version (3.0.0) might be outdated. Consider the following:

Update to the latest stable Flutter version or the specific version required by your project.
Ensure that this version is compatible with your project's dependencies and SDK constraints.
Example:

- name: Set up Flutter  
  uses: subosito/flutter-action@v2  
  with:  
    flutter-version: '3.10.0' # Update to the latest stable version or your project's required version  
Also, verify that this version matches the one specified in your pubspec.yaml file.

The following scripts were executed for the analysis:

Script:

