name: Deployment Tests

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "junqo_back/**"
      - "junqo_front/**"
      - ".github/workflows/deployment-tests.yml"
  workflow_dispatch:

jobs:
  deployment-dev-tests:
    uses: ./.github/workflows/deployment-test-template.yml
    with:
      compose_file: docker-compose.dev.yaml

  deployment-prod-tests:
    uses: ./.github/workflows/deployment-test-template.yml
    with:
      compose_file: docker-compose.yaml