name: Deployment Tests

on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  deployment-dev-tests:
    uses: ./.github/workflows/deployment-test-template.yml
    with:
      compose_file: docker-compose.dev.yaml

  deployment-prod-tests:
    needs: deployment-dev-tests
    uses: ./.github/workflows/deployment-test-template.yml
    with:
      compose_file: docker-compose.yaml
