# Launch tests for the frontend
name: Frontend Tests

on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  test:
    if: |
      github.event_name == 'pull_request' &&
      (github.event.action == 'opened' ||
        (github.event.action == 'synchronize' &&
          (contains(github.event.pull_request.changed_files, 'junqo_front/**') ||
            contains(github.event.pull_request.changed_files, '.github/workflows/front-tests.yml')
          )
        )
      )
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: junqo_front/pubspec.yaml

    - run: flutter --version

    - name: Install dependencies
      run: flutter pub get
      working-directory: junqo_front

    - name: Run Flutter tests
      run: flutter test
      working-directory: junqo_front
