# Launch tests for the frontend
name: Frontend Tests

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "junqo_front/**"
      - ".github/workflows/front-tests.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: junqo_front/pubspec.yaml

    - run: flutter --version

    - name: Install dependencies
      run: flutter pub get
      working-directory: junqo_front

    - name: Generate graphql types
      run: cp ../schemas/*.graphql ./lib/schemas/; dart run build_runner build
      working-directory: junqo_front

    - name: Run Flutter tests
      run: flutter test
      working-directory: junqo_front
